import { v4 as uuid } from "uuid";
import { prisma } from "../../db";
import { Deck } from "../../types";

const deckId = "deck-850-basic";

const deck: Deck = {
    id: deckId,
    name: "850 Basic Words",
    description: "850 từ tiếng Anh cơ bản (Ogden's Basic English)",
    category: "things_general",
    totalWords: 850,
    version: 1,
    language: "vi",
};

// Helper to create word object with optional phonetic and examples
const createWord = (
    headword: string,
    partOfSpeech: string,
    meaningVi: string,
    phonetic?: string,
    exampleEn?: string,
    exampleVi?: string
) => ({
    headword,
    partOfSpeech,
    meaningVi,
    phonetic,
    exampleEn,
    exampleVi,
});

const words = [
    // Previous words
    createWord("Come", "verb", "Đến"),
    createWord("Get", "verb", "Đạt được"),
    createWord("Give", "verb", "Đưa"),
    createWord("Keep", "verb", "Giữ"),
    createWord("Let", "verb", "Để cho"),
    createWord("Make", "verb", "Làm cho"),
    createWord("Put", "verb", "Đặt, để"),
    createWord("Seem", "verb", "Dường như"),
    createWord("Take", "verb", "Cầm lấy"),
    createWord("Be", "verb", "Là, thì, ở"),
    createWord("Do", "verb", "Làm"),
    createWord("Have", "verb", "Có được"),
    createWord("Say", "verb", "Nói"),
    createWord("See", "verb", "Nhìn"),
    createWord("Send", "verb", "Gửi"),
    createWord("May", "modal verb", "Có thể"),
    createWord("Will", "modal verb", "Sẽ"),
    createWord("About", "preposition", "Về"),
    createWord("Across", "preposition", "Băng qua"),
    createWord("Against", "preposition", "Chống lại"),
    createWord("Among", "preposition", "Trong số"),
    createWord("At", "preposition", "Ở tại"),
    createWord("Before", "adverb", "Trước"),
    createWord("Between", "preposition", "Ở giữa"),
    createWord("Through", "preposition", "Xuyên qua"),
    createWord("To", "preposition", "Đến"),
    createWord("Under", "preposition", "Ở phía dưới"),
    createWord("Up", "adverb", "Ở phía trên"),
    createWord("With", "preposition", "Cùng"),
    createWord("As", "adverb", "Như là"),
    createWord("For", "preposition", "Để cho"),
    createWord("Of", "preposition", "Của"),
    createWord("Till", "conjunction", "Đến tận khi"),
    createWord("Than", "conjunction", "Hơn"),
    createWord("A", "article", "Một, một cái"),
    createWord("The", "article", "Cái, con, người (đã xác định)"),
    createWord("All", "adjective", "Tất cả"),
    createWord("Any", "adjective", "Bất kỳ"),
    createWord("Every", "adjective", "Mọi"),
    createWord("No", "adjective", "Không"),
    createWord("Other", "adjective", "Cái khác"),
    createWord("Some", "adjective", "Một vài"),
    createWord("Such", "adjective", "Như thế"),
    createWord("That", "pronoun", "Cái đó"),
    createWord("This", "pronoun", "Cái này"),
    createWord("I", "pronoun", "Tôi"),
    createWord("She", "pronoun", "Cô ta, bà ta"),
    createWord("He", "pronoun", "Ông ta, anh ta"),
    createWord("You", "pronoun", "Bạn, các bạn"),
    createWord("Who", "pronoun", "Ai"),
    createWord("And", "conjunction", "Và"),
    createWord("Because", "conjunction", "Bởi vì"),
    createWord("But", "conjunction", "Nhưng"),
    createWord("Or", "conjunction", "Hoặc là"),
    createWord("If", "conjunction", "Nếu"),
    createWord("Though", "conjunction", "Mặc dù"),
    createWord("While", "conjunction", "Trong khi"),
    createWord("How", "adverb", "Như thế nào"),
    createWord("When", "adverb", "Khi nào"),
    createWord("Where", "adverb", "Ở đâu"),
    createWord("Why", "adverb", "Tại sao"),
    createWord("Again", "adverb", "Lặp lại"),
    createWord("Ever", "adverb", "Đã từng"),
    createWord("Far", "adjective", "Xa"),
    createWord("Forward", "adverb", "Phía trước"),
    createWord("Here", "adverb", "Ở đây"),
    createWord("Near", "adjective", "Ở gần đây"),
    createWord("Now", "adverb", "Bây giờ"),
    createWord("Out", "adverb", "Bên ngoài"),
    createWord("Still", "adverb", "Vẫn"),
    createWord("Then", "adverb", "Sau đó"),
    createWord("There", "adverb", "Ở đó"),
    createWord("Together", "adverb", "Cùng nhau"),
    createWord("Well", "adverb", "Tốt"),
    createWord("Almost", "adverb", "Hầu như"),
    createWord("Enough", "adjective", "Đủ"),
    createWord("Even", "adverb", "Ngay cả"),
    createWord("Little", "adjective", "Một ít"),
    createWord("Much", "adjective", "Nhiều"),
    createWord("Not", "adverb", "Không"),
    createWord("Only", "adverb", "Chỉ"),
    createWord("Quite", "adverb", "Hoàn toàn"),
    createWord("So", "adverb", "Vì thế"),
    createWord("Very", "adjective", "Rất"),
    createWord("Tomorrow", "noun", "Ngày mai"),
    createWord("Yesterday", "noun", "Hôm qua"),
    createWord("North", "noun", "Phương bắc"),
    createWord("South", "noun", "Phương nam"),
    createWord("East", "noun", "Phương đông"),
    createWord("West", "noun", "Phương tây"),
    createWord("Please", "verb", "Xin vui lòng"),
    createWord("Yes", "noun", "Vâng"),

    // New words from images (Selection)
    createWord("Account", "noun", "Tài khoản"),
    createWord("Act", "verb", "Hành động"),
    createWord("Addition", "noun", "Thêm"),
    createWord("Adjustment", "noun", "Điều chỉnh"),
    createWord("Advertisement", "noun", "Quảng cáo"),
    createWord("Agreement", "noun", "Sự đồng ý"),
    createWord("Air", "noun", "Không khí"),
    createWord("Amount", "noun", "Số lượng"),
    createWord("Amusement", "noun", "Sự làm vui lòng"),
    createWord("Animal", "noun", "Động vật"),
    createWord("Answer", "verb", "Trả lời"),
    createWord("Apparatus", "noun", "Dụng cụ"),
    createWord("Approval", "noun", "Sự chấp thuận"),
    createWord("Argument", "noun", "Sự tranh cãi"),
    createWord("Art", "noun", "Nghệ thuật"),
    createWord("Attack", "verb", "Sự tấn công"),
    createWord("Attempt", "noun", "Sự cố gắng"),
    createWord("Attention", "noun", "Sự có mặt"),
    createWord("Attraction", "noun", "Sự thu hút"),
    createWord("Authority", "noun", "Sự thẩm quyền"),
    createWord("Back", "noun", "Lưng"),
    createWord("Balance", "noun", "Cân bằng"),
    createWord("Base", "noun", "Cơ sở"),
    createWord("Behavior", "noun", "Cư xử"),
    createWord("Belief", "noun", "Niềm tin"),
    createWord("Birth", "noun", "Sự sinh sản"),
    createWord("Bit", "noun", "Một ít"),
    createWord("Bite", "verb", "Cắn"),
    createWord("Blood", "noun", "Máu"),
    createWord("Blow", "verb", "Thổi"),
    createWord("Body", "noun", "Cơ thể"),
    createWord("Brass", "noun", "Đồng thau"),
    createWord("Bread", "noun", "Bánh mỳ"),
    createWord("Breath", "noun", "Hơi thở"),
    createWord("Brother", "noun", "Anh, em trai"),
    createWord("Building", "noun", "Tòa nhà"),
    createWord("Burn", "noun", "Bốc cháy"),
    createWord("Burst", "noun", "Bùng nổ"),
    createWord("Business", "noun", "Công việc"),
    createWord("Butter", "noun", "Bơ"),
    createWord("Canvas", "noun", "Vải bạt"),
    createWord("Care", "noun", "Sự thận trọng"),
    createWord("Cause", "noun", "Gây nên"),
    createWord("Chalk", "noun", "Viên phấn"),
    createWord("Chance", "noun", "Cơ hội"),
    createWord("Change", "noun", "Thay đổi"),
    createWord("Cloth", "noun", "Vải vóc"),
    createWord("Coal", "noun", "Than đá"),
    createWord("Color", "noun", "Màu sắc"),
    createWord("Comfort", "noun", "Sự tiện nghi"),
    createWord("Committee", "noun", "Ủy ban"),
    createWord("Company", "noun", "Công ty"),
    createWord("Comparison", "noun", "Sự so sánh"),
    createWord("Competition", "noun", "Sự cạnh tranh"),
    createWord("Condition", "noun", "Điều kiện"),
    createWord("Connection", "noun", "Sự liên kết"),
    createWord("Control", "verb", "Kiểm soát"),
    createWord("Cook", "verb", "Nấu"),
    createWord("Copper", "noun", "Đồng"),
    createWord("Copy", "verb", "Sao chép"),
    createWord("Cork", "noun", "Nút chai"),
    createWord("Cotton", "noun", "Bông"),
    createWord("Cough", "verb", "Ho"),
    createWord("Country", "noun", "Quốc gia"),
    createWord("Cover", "noun", "Bao phủ"),
    createWord("Crack", "noun", "Đường nứt"),
    createWord("Credit", "noun", "Tín dụng"),
    createWord("Crime", "noun", "Tội phạm"),
    createWord("Crush", "verb", "Ép"),
    createWord("Cry", "verb", "Khóc"),
    createWord("Current", "noun", "Hiện hành"),
    createWord("Curve", "verb", "Khắc chạm"),
    createWord("Damage", "verb", "Phá hủy"),
    createWord("Danger", "noun", "Nguy hiểm"),
    createWord("Daughter", "noun", "Con gái"),
    createWord("Day", "noun", "Ngày"),
    createWord("Death", "noun", "Cái chết"),
    createWord("Debt", "noun", "Nợ"),
    createWord("Decision", "noun", "Quyết định"),
    createWord("Degree", "noun", "Độ"),
    createWord("Design", "verb", "Thiết kế"),
    createWord("Desire", "verb", "Mong muốn"),
    createWord("Destruction", "noun", "Sự phá hủy"),
    createWord("Detail", "noun", "Chi tiết"),
    createWord("Development", "noun", "Sự phát triển"),
    createWord("Digestion", "noun", "Sự tiêu hóa"),
    createWord("Direction", "noun", "Phương hướng"),
    createWord("Discovery", "noun", "Sự khám phá"),
    createWord("Discussion", "noun", "Thảo luận"),
    createWord("Disease", "noun", "Bệnh tật"),
    createWord("Disgust", "noun", "Sự ghê tởm"),
    createWord("Distance", "noun", "Khoảng cách"),
    createWord("Distribution", "noun", "Sự phân phối"),
    createWord("Division", "noun", "Sự phân chia"),
    createWord("Doubt", "noun", "Sự nghi ngờ"),
    createWord("Drink", "verb", "Uống"),
    createWord("Driving", "noun", "Lái xe"),
    createWord("Dust", "noun", "Bụi bặm"),
    createWord("Earth", "noun", "Trái đất"),
    createWord("Edge", "noun", "Bờ mép"),
    createWord("Education", "noun", "Giáo dục"),
    createWord("Effect", "verb", "Tác động"),
    createWord("End", "noun", "Kết thúc"),
    createWord("Error", "noun", "Lỗi"),
    createWord("Event", "noun", "Sự kiện"),
    createWord("Example", "noun", "Ví dụ"),
    createWord("Exchange", "noun", "Trao đổi"),
    createWord("Existence", "noun", "Sự hiện hữu"),
    createWord("Expansion", "noun", "Sự bành trướng"),
    createWord("Experience", "noun", "Kinh nghiệm"),
    createWord("Expert", "noun", "Chuyên gia"),
    createWord("Fact", "noun", "Thực tế"),
    createWord("Fall", "noun", "Rơi, thác"),
    createWord("Family", "noun", "Gia đình"),
    createWord("Father", "noun", "Cha"),
    createWord("Fear", "noun", "Nỗi sợ hãi"),
    createWord("Feeling", "noun", "Cảm xúc"),
    createWord("Fiction", "noun", "Viễn tưởng"),
    createWord("Field", "noun", "Lĩnh vực"),
    createWord("Fight", "noun", "Cuộc chiến"),
    createWord("Fire", "noun", "Lửa"),
    createWord("Flame", "noun", "Ngọn lửa"),
    createWord("Flight", "noun", "Chuyến bay"),
    createWord("Flower", "noun", "Bông hoa"),
    createWord("Fold", "noun", "Nếp gấp"),
    createWord("Food", "noun", "Thức ăn"),
    createWord("Force", "noun", "Lực lượng"),
    createWord("Form", "noun", "Hình thức"),
    createWord("Friend", "noun", "Bạn hữu"),
    createWord("Front", "noun", "Phía trước"),
    createWord("Fruit", "noun", "Trái cây"),
    createWord("Glass", "noun", "Kính, gương"),
    createWord("Gold", "noun", "Vàng"),
    createWord("Government", "noun", "Chính phủ"),
    createWord("Grain", "noun", "Hạt"),
    createWord("Grass", "noun", "Cỏ"),
    createWord("Grip", "noun", "Sự nắm chắc"),
    createWord("Group", "noun", "Nhóm"),
    createWord("Growth", "noun", "Sự phát triển"),
    createWord("Guide", "verb", "Hướng dẫn"),
    createWord("Harbour", "noun", "Hải cảng"),
    createWord("Harmony", "noun", "Sự hòa hợp"),
    createWord("Hate", "verb", "Ghét"),
    createWord("Hearing", "noun", "Sự nghe"),
    createWord("Heat", "noun", "Sức nóng"),
    createWord("Help", "verb", "Giúp đỡ"),
    createWord("History", "noun", "Lịch sử"),
    createWord("Hole", "noun", "Cái lỗ"),
    createWord("Hope", "verb", "Hy vọng"),
    createWord("Hour", "noun", "Giờ"),
    createWord("Humour", "noun", "Hài hước"),
    createWord("Ice", "noun", "Băng, nước đá"),
    createWord("Idea", "noun", "Ý tưởng"),
    createWord("Impulse", "noun", "Xúc động"),
    createWord("Increase", "verb", "Gia tăng"),
    createWord("Industry", "noun", "Ngành CN"),
    createWord("Ink", "noun", "Mực"),
    createWord("Insect", "noun", "Côn trùng"),
    createWord("Instrument", "noun", "Dụng cụ"),
    createWord("Insurance", "noun", "Bảo hiểm"),
    createWord("Interest", "noun", "Mối quan tâm"),
    createWord("Invention", "noun", "Phát minh"),
    createWord("Iron", "noun", "Sắt"),
    createWord("Jelly", "noun", "Thạch"),
    createWord("Join", "noun", "Mối nối"),
    createWord("Journey", "noun", "Chuyến đi"),
    createWord("Judge", "verb", "Phán xử"),
    createWord("Jump", "verb", "Nhảy"),
    createWord("Kick", "verb", "Đá"),
    createWord("Kiss", "verb", "Hôn"),
    createWord("Knowledge", "noun", "Kiến thức"),
    createWord("Land", "noun", "Đất"),
    createWord("Language", "noun", "Ngôn ngữ"),
    createWord("Laugh", "verb", "Cười"),
    createWord("Law", "noun", "Luật"),
    createWord("Lead", "verb", "Dẫn đến"),
    createWord("Learning", "noun", "Học tập"),
    createWord("Leather", "noun", "Da"),
    createWord("Letter", "noun", "Thư, chữ cái"),
    createWord("Level", "noun", "Mức"),
    createWord("Lift", "noun", "Thang máy"),
    createWord("Light", "noun", "Ánh sáng"),
    createWord("Limit", "noun", "Giới hạn"),
    createWord("Linen", "noun", "Vải lanh"),
    createWord("Liquid", "noun", "Chất lỏng"),
    createWord("List", "noun", "Danh sách"),
    createWord("Look", "verb", "Nhìn"),
    createWord("Loss", "noun", "Mất"),
    createWord("Love", "noun", "Tình yêu"),
    createWord("Machine", "noun", "Máy móc"),
    createWord("Man", "noun", "Người, đàn ông"),
    createWord("Manager", "noun", "Người quản lý"),
    createWord("Mark", "noun", "Dấu vết"),
    createWord("Market", "noun", "Chợ"),
    createWord("Mass", "noun", "Khối lượng"),
    createWord("Meal", "noun", "Bữa ăn"),
    createWord("Measure", "noun", "Đo lường"),
    createWord("Meat", "noun", "Thịt"),
    createWord("Meeting", "noun", "Cuộc họp"),
    createWord("Memory", "noun", "Trí nhớ"),
    createWord("Metal", "noun", "Kim loại"),
    createWord("Middle", "noun", "Ở giữa"),
    createWord("Milk", "noun", "Sữa"),
    createWord("Mind", "noun", "Tâm trí"),
    createWord("Mine", "noun", "Của tôi"),
    createWord("Minute", "noun", "Phút"),
    createWord("Mist", "noun", "Sương mù"),
    createWord("Money", "noun", "Tiền"),
    createWord("Month", "noun", "Tháng"),
    createWord("Morning", "noun", "Buổi sáng"),
    createWord("Mother", "noun", "Mẹ"),
    createWord("Motion", "noun", "Chuyển động"),
    createWord("Mountain", "noun", "Núi"),
    createWord("Move", "verb", "Di chuyển"),
    createWord("Music", "noun", "Âm nhạc"),
    createWord("Name", "noun", "Tên"),
    createWord("Nation", "noun", "Quốc gia"),
    createWord("Need", "noun", "Nhu cầu"),
    createWord("News", "noun", "Tin tức"),
    createWord("Night", "noun", "Đêm"),
    createWord("Noise", "noun", "Tiếng ồn"),
    createWord("Note", "noun", "Ghi chú"),
    createWord("Number", "noun", "Số"),
    createWord("Observation", "noun", "Sự quan sát"),
    createWord("Offer", "noun", "Đề nghị"),
    createWord("Oil", "noun", "Dầu"),
    createWord("Operation", "noun", "Hoạt động"),
    createWord("Opinion", "noun", "Ý kiến"),
    createWord("Order", "noun", "Yêu cầu"),
    createWord("Organization", "noun", "Tổ chức"),
    createWord("Ornament", "noun", "Trang hoàng"),
    createWord("Owner", "noun", "Người chủ"),
    createWord("Page", "noun", "Trang"),
    createWord("Pain", "noun", "Cơn đau"),
    createWord("Paint", "noun", "Sơn"),
    createWord("Paper", "noun", "Giấy"),
    createWord("Part", "noun", "Phần"),
    createWord("Paste", "noun", "Hồ dán"),
    createWord("Payment", "noun", "Thanh toán"),
    createWord("Peace", "noun", "Hòa bình"),
    createWord("Person", "noun", "Người"),
    createWord("Place", "noun", "Nơi chốn"),
    createWord("Plant", "noun", "Thực vật"),
    createWord("Play", "noun", "Vở kịch"),
    createWord("Pleasure", "noun", "Niềm vui"),
    createWord("Point", "noun", "Điểm"),
    createWord("Poison", "noun", "Chất độc"),
    createWord("Polish", "noun", "Đánh bóng"),
    createWord("Porter", "noun", "Người khuân vác"),
    createWord("Position", "noun", "Vị trí"),
    createWord("Powder", "noun", "Bột"),
    createWord("Power", "noun", "Quyền lực"),
    createWord("Price", "noun", "Giá cả"),
    createWord("Print", "noun", "In ấn"),
    createWord("Process", "noun", "Quá trình"),
    createWord("Produce", "verb", "Sản xuất"),
    createWord("Profit", "noun", "Lợi nhuận"),
    createWord("Property", "noun", "Tài sản"),
    createWord("Prose", "noun", "Văn xuôi"),
    createWord("Protest", "noun", "Phản đối"),
    createWord("Pull", "verb", "Kéo"),
    createWord("Punishment", "noun", "Hình phạt"),
    createWord("Purpose", "noun", "Mục đích"),
    createWord("Push", "verb", "Đẩy"),
    createWord("Quality", "noun", "Chất lượng"),
    createWord("Question", "noun", "Câu hỏi"),
    createWord("Rain", "noun", "Mưa"),
    createWord("Range", "noun", "Phạm vi"),
    createWord("Rate", "noun", "Tỷ lệ"),
    createWord("Ray", "noun", "Tia"),
    createWord("Reaction", "noun", "Phản ứng"),
    createWord("Reading", "noun", "Đọc"),
    createWord("Reason", "noun", "Lý do"),
    createWord("Record", "noun", "Kỷ lục"),
    createWord("Regret", "noun", "Hối tiếc"),
    createWord("Relation", "noun", "Mối quan hệ"),
    createWord("Religion", "noun", "Tôn giáo"),
    createWord("Representative", "noun", "Đại diện"),
    createWord("Request", "verb", "Yêu cầu"),
    createWord("Respect", "noun", "Kính trọng"),
    createWord("Rest", "noun", "Nghỉ ngơi"),
    createWord("Reward", "noun", "Phần thưởng"),
    createWord("Rhythm", "noun", "Nhịp điệu"),
    createWord("Rice", "noun", "Gạo"),
    createWord("River", "noun", "Sông"),
    createWord("Road", "noun", "Con đường"),
    createWord("Roll", "noun", "Cuộn"),
    createWord("Room", "noun", "Phòng"),
    createWord("Rub", "verb", "Cọ xát"),
    createWord("Rule", "noun", "Quy tắc"),
    createWord("Run", "verb", "Chạy"),
    createWord("Salt", "noun", "Muối"),
    createWord("Sand", "noun", "Cát"),
    createWord("Scale", "noun", "Quy mô"),
    createWord("Science", "noun", "Khoa học"),
    createWord("Sea", "noun", "Biển"),
    createWord("Seat", "noun", "Chỗ ngồi"),
    createWord("Secretary", "noun", "Thư ký"),
    createWord("Selection", "noun", "Sự lựa chọn"),
    createWord("Self", "noun", "Bản thân"),
    createWord("Sense", "noun", "Giác quan"),
    createWord("Servant", "noun", "Người hầu"),
    createWord("Sex", "noun", "Giới tính"),
    createWord("Shade", "noun", "Bóng râm"),
    createWord("Shake", "verb", "Rung, lắc"),
    createWord("Shame", "noun", "Sự xấu hổ"),
    createWord("Shock", "noun", "Cú sốc"),
    createWord("Side", "noun", "Cạnh, bên"),
    createWord("Sign", "noun", "Dấu hiệu"),
    createWord("Silk", "noun", "Lụa"),
    createWord("Silver", "noun", "Bạc"),
    createWord("Sister", "noun", "Chị, em gái"),
    createWord("Size", "noun", "Kích thước"),
    createWord("Sky", "noun", "Bầu trời"),
    createWord("Sleep", "verb", "Ngủ"),
    createWord("Slip", "verb", "Trượt"),
    createWord("Slope", "noun", "Dốc"),
    createWord("Smash", "verb", "Đập tan"),
    createWord("Smell", "verb", "Ngửi"),
    createWord("Smile", "verb", "Cười"),
    createWord("Smoke", "verb", "Hút thuốc"),
    createWord("Sneeze", "verb", "Hắt hơi"),
    createWord("Snow", "noun", "Tuyết"),
    createWord("Soap", "noun", "Xà phòng"),
    createWord("Society", "noun", "Xã hội"),
    createWord("Son", "noun", "Con trai"),
    createWord("Song", "noun", "Bài hát"),
    createWord("Sort", "noun", "Loại"),
    createWord("Sound", "noun", "Âm thanh"),
    createWord("Soup", "noun", "Súp"),
    createWord("Space", "noun", "Không gian"),
    createWord("Stage", "noun", "Sân khấu"),
    createWord("Start", "verb", "Bắt đầu"),
    createWord("Statement", "noun", "Lời tuyên bố"),
    createWord("Steam", "noun", "Hơi nước"),
    createWord("Steel", "noun", "Thép"),
    createWord("Step", "noun", "Bước"),
    createWord("Stitch", "noun", "Mũi khâu"),
    createWord("Stone", "noun", "Đá"),
    createWord("Stop", "verb", "Dừng lại"),
    createWord("Story", "noun", "Câu chuyện"),
    createWord("Stretch", "verb", "Căng ra"),
    createWord("Structure", "noun", "Cấu trúc"),
    createWord("Substance", "noun", "Chất"),
    createWord("Sugar", "noun", "Đường"),
    createWord("Suggestion", "noun", "Sự gợi ý"),
    createWord("Summer", "noun", "Mùa hè"),
    createWord("Support", "verb", "Ủng hộ"),
    createWord("Surprise", "noun", "Sự ngạc nhiên"),
    createWord("Swim", "verb", "Bơi"),
    createWord("System", "noun", "Hệ thống"),
    createWord("Talk", "verb", "Nói chuyện"),
    createWord("Taste", "verb", "Nếm"),
    createWord("Tax", "noun", "Thuế"),
    createWord("Teaching", "noun", "Sự dạy dỗ"),
    createWord("Tendency", "noun", "Xu hướng"),
    createWord("Test", "noun", "Bài kiểm tra"),
    createWord("Theory", "noun", "Lý thuyết"),
    createWord("Thing", "noun", "Sự vật"),
    createWord("Thought", "noun", "Suy nghĩ"),
    createWord("Thunder", "noun", "Sấm"),
    createWord("Time", "noun", "Thời gian"),
    createWord("Tin", "noun", "Thiếc"),
    createWord("Top", "noun", "Đỉnh"),
    createWord("Touch", "verb", "Chạm"),
    createWord("Trade", "noun", "Thương mại"),
    createWord("Transport", "verb", "Vận chuyển"),
    createWord("Trick", "noun", "Mẹo"),
    createWord("Trouble", "noun", "Rắc rối"),
    createWord("Turn", "verb", "Xoay"),
    createWord("Twist", "verb", "Xoắn"),
    createWord("Unit", "noun", "Đơn vị"),
    createWord("Use", "verb", "Sử dụng"),
    createWord("Value", "noun", "Giá trị"),
    createWord("Verse", "noun", "Thơ"),
    createWord("Vessel", "noun", "Bình chứa"),
    createWord("View", "noun", "Quan điểm"),
    createWord("Voice", "noun", "Giọng nói"),
    createWord("Walk", "verb", "Đi bộ"),
    createWord("War", "noun", "Chiến tranh"),
    createWord("Wash", "verb", "Rửa"),
    createWord("Waste", "noun", "Lãng phí"),
    createWord("Water", "noun", "Nước"),
    createWord("Wave", "noun", "Sóng"),
    createWord("Wax", "noun", "Sáp"),
    createWord("Way", "noun", "Cách thức"),
    createWord("Weather", "noun", "Thời tiết"),
    createWord("Week", "noun", "Tuần"),
    createWord("Weight", "noun", "Trọng lượng"),
    createWord("Wind", "noun", "Gió"),
    createWord("Wine", "noun", "Rượu"),
    createWord("Winter", "noun", "Mùa đông"),
    createWord("Woman", "noun", "Phụ nữ"),
    createWord("Wood", "noun", "Gỗ"),
    createWord("Wool", "noun", "Len"),
    createWord("Word", "noun", "Từ"),
    createWord("Work", "noun", "Công việc"),
    createWord("Wound", "noun", "Vết thương"),
    createWord("Writing", "noun", "Viết"),
    createWord("Year", "noun", "Năm"),

    // Additional words from latest update
    createWord("Manage", "verb", "Quản lý"),
    createWord("Tall", "adjective", "Cao"),
    createWord("Round", "adjective", "Tròn"),
    createWord("Same", "adjective", "Cùng"),
    createWord("Second", "noun", "Thứ nhì"),
    createWord("Opposite", "adjective", "Đối diện"),
    createWord("Public", "adjective", "Công cộng"),
    createWord("Rough", "adjective", "Gồ ghề"),
    createWord("Sad", "adjective", "Buồn"),
    createWord("Safe", "adjective", "An toàn"),
    createWord("Secret", "noun", "Bí mật"),
    createWord("Short", "adjective", "Ngắn"),
    createWord("Shut", "verb", "Đóng kín"),
    createWord("Different", "adjective", "Khác"),
    createWord("Dirty", "adjective", "Bẩn"),
    createWord("Dry", "adjective", "Khô"),
    createWord("False", "adjective", "Giả"),
    createWord("Feeble", "adjective", "Yếu đuối"),
    createWord("Female", "noun", "Giống cái"),
    createWord("Foolish", "adjective", "Dại dột"),
    createWord("Future", "noun", "Tương lai"),
    createWord("Soft", "adjective", "Mềm mại"),
    createWord("Solid", "adjective", "Cứng chắc"),
    createWord("Special", "adjective", "Đặc biệt"),
    createWord("Strange", "adjective", "Lạ"),
    createWord("Thin", "adjective", "Mỏng"),
    createWord("White", "adjective", "Màu trắng"),
    createWord("Wrong", "adjective", "Sai lầm"),
    createWord("Simple", "adjective", "Đơn giản"),
    createWord("Slow", "adjective", "Chậm"),
    createWord("Small", "adjective", "Nhỏ"),
    createWord("Ability", "noun", "Khả năng"),
    createWord("Academic", "noun", "Thuộc nhà trường"),
    createWord("Access", "noun", "Đường vào"),
    createWord("Accident", "noun", "Tai nạn"),
    createWord("Alone", "adjective", "Chỉ một mình"),
    createWord("Along", "preposition", "Dọc theo"),
    createWord("Affect", "verb", "Tác động"),
    createWord("Afford", "verb", "Đủ khả năng"),
    createWord("Advice", "noun", "Lời khuyên"),
    createWord("Advise", "verb", "Khuyên"),
    createWord("All right", "adjective", "Được"),
    createWord("Alternative", "adjective", "Thay thế"),
    createWord("Announce", "verb", "Tuyên bố"),
    createWord("Attractive", "adjective", "Cuốn hút"),
    createWord("Average", "adjective", "Trung bình"),
    createWord("Avoid", "verb", "Tránh"),
    createWord("Band", "noun", "Ban nhạc"),
    createWord("Bank", "noun", "Ngân hàng"),
    createWord("Bar", "noun", "Quán rượu"),
    createWord("Beat", "verb", "Đánh đập"),
    createWord("Area", "noun", "Khu vực"),
    createWord("Attach", "verb", "Dán"),
    createWord("Atmosphere", "noun", "Khí quyển"),
    createWord("Appoint", "verb", "Bổ nhiệm"),
    createWord("Disappear", "verb", "Biến mất"),
    createWord("Appear", "verb", "Xuất hiện"),
    createWord("Candidate", "noun", "Người ứng cử"),
    createWord("Pan", "noun", "Chảo"),
    createWord("Chairman", "noun", "Chủ tịch"),
    createWord("Confirm", "verb", "Xác nhận"),
    createWord("Action", "noun", "Hành động"),

    // Batch 2: Words 149-308 (from second set of images)
    createWord("Earth", "noun", "Trái đất", "/ɜːθ/"),
    createWord("East", "noun", "Hướng đông, phương đông", "/iːst/"),
    createWord("Edge", "noun", "Bờ, lề", "/edʒ/"),
    createWord("Education", "noun", "Sự giáo dục, giáo dục", "/ˌedjuˈkeɪʃən/"),
    createWord("Effect", "noun", "Tác động", "/ɪˈfekt/"),
    createWord("Egg", "noun", "Quả trứng", "/eg/"),
    createWord("End", "noun", "Sự kết thúc", "/end/"),
    createWord("Engine", "noun", "Động cơ, máy", "/ˈendʒɪn/"),
    createWord("Error", "noun", "Lỗi, sai lầm, sự có", "/ˈerər/"),
    createWord("Event", "noun", "Sự kiện", "/ɪˈvent/"),
    createWord("Example", "noun", "Ví dụ", "/ɪgˈzæmpl/"),
    createWord("Exchange", "noun", "Trao đổi, đổi, trao", "/ɪksˈtʃeɪndʒ/"),
    createWord("Existence", "noun", "Sự hiện tại", "/ɪgˈzɪstəns/"),
    createWord("Expansion", "noun", "Sự mở rộng, sự bành trướng", "/ɪkˈspænʃən/"),
    createWord("Experience", "noun", "Kinh nghiệm", "/ɪkˈspɪərɪəns/"),
    createWord("Expert", "noun", "Chuyên gia", "/ˈekspɜːt/"),
    createWord("Eye", "noun", "Mắt", "/aɪ/"),
    createWord("Face", "noun", "Mặt", "/feɪs/"),
    createWord("Fact", "noun", "Thực tế, sự thật", "/fækt/"),
    createWord("Family", "noun", "Gia đình", "/ˈfæməli/"),
    createWord("Farm", "noun", "Nông trại", "/fɑːmə/"),
    createWord("Father", "noun", "Bố", "/ˈfɑːðər/"),
    createWord("Fear", "noun", "Sự sợ hãi", "/fɪə/"),
    createWord("Feather", "noun", "Bộ lông", "/ˈfeðər/"),
    createWord("Fiction", "noun", "Cấm bi, sư hư cấu, tiểu thuyết, được tưởng tượng", "/ˈfɪkʃən/"),
    createWord("Female", "noun", "Giống cái", "/ˈfiːmeɪl/"),
    createWord("Field", "noun", "Cánh đồng", "/fiːld/"),
    createWord("Finger", "noun", "Ngón tay", "/ˈfɪŋgər/"),
    createWord("Fire", "noun", "Ngọn lửa", "/faɪə/"),
    createWord("Fish", "noun", "Cá", "/fɪʃ/"),
    createWord("Flag", "noun", "Ngọn cờ", "/flæg/"),
    createWord("Flame", "noun", "Ngọn lửa", "/fleɪm/"),
    createWord("Flat", "noun", "Căn hộ", "/flæt/"),
    createWord("Flight", "noun", "Chuyến bay", "/flaɪt/"),
    createWord("Floor", "noun", "Sàn nhà", "/flɔː/"),
    createWord("Flower", "noun", "Hoa", "/ˈflaʊə/"),
    createWord("Food", "noun", "Thức ăn, lương thực", "/fuːd/"),
    createWord("Foot", "noun", "Bàn chân", "/fʊt/"),
    createWord("Fork", "noun", "Cái nĩa", "/fɔːk/"),
    createWord("Form", "noun", "Mẫu đơn sư", "/fɔːm/"),
    createWord("Fowl", "noun", "Gia cầm", "/faʊl/"),
    createWord("Frame", "noun", "Khung, cơ cấu", "/freɪm/"),
    createWord("Friend", "noun", "Bạn", "/frend/"),
    createWord("Front", "noun", "Mặt trước", "/frʌnt/"),
    createWord("Fruit", "noun", "Hoa quả", "/fruːt/"),
    createWord("Future", "noun", "Tương lai, sắu này", "/ˈfjuːtʃər/"),
    createWord("Garden", "noun", "Vườn", "/ˈgɑːdən/"),
    createWord("Girl", "noun", "Cô gái", "/gɜːl/"),
    createWord("Glass", "noun", "Cốc thủy tinh", "/glɑːs/"),
    createWord("Glove", "noun", "Tất tay", "/glʌv/"),
    createWord("Goat", "noun", "Con dê", "/gəʊt/"),
    createWord("Gold", "noun", "Vàng", "/gəʊld/"),
    createWord("Government", "noun", "Chính phủ, chính quyền", "/ˈgʌvənmənt/"),
    createWord("Grain", "noun", "Ngũ cốc", "/greɪn/"),
    createWord("Grass", "noun", "Cỏ", "/grɑːs/"),
    createWord("Group", "noun", "Nhóm", "/gruːp/"),
    createWord("Growth", "noun", "Sự tăng trưởng, sự gia tăng", "/grəʊθ/"),
    createWord("Gun", "noun", "Súng", "/gʌn/"),
    createWord("Hair", "noun", "Mái tóc", "/heə/"),
    createWord("Hammer", "noun", "Cái búa", "/ˈhæmə/"),
    createWord("Hand", "noun", "Bàn tay", "/hænd/"),
    createWord("Hanging", "noun", "Bức tranh, bức tranh treo", "/ˈhæŋɪŋ/"),
    createWord("Harbor", "noun", "Bến cảng", "/ˈhɑːbə/"),
    createWord("Harmony", "noun", "Sự hài hòa, sư cân đối", "/ˈhɑːməni/"),
    createWord("Hat", "noun", "Cái mũ", "/hæt/"),
    createWord("Head", "noun", "Đầu", "/hed/"),
    createWord("Hearing", "noun", "Thính giác", "/ˈhɪərɪŋ/"),
    createWord("Heart", "noun", "Trái tim", "/hɑːt/"),
    createWord("Heat", "noun", "Sức nóng, hơi nóng", "/hiːt/"),
    createWord("History", "noun", "Lịch sử", "/ˈhɪstəri/"),
    createWord("Hole", "noun", "Hố sâu, lỗ hổng", "/həʊl/"),
    createWord("Hook", "noun", "Cái móc", "/hʊk/"),
    createWord("Hope", "noun", "Niềm hi vọng", "/həʊp/"),
    createWord("Horn", "noun", "Sừng ngựa", "/hɔːn/"),
    createWord("Horse", "noun", "Con ngựa", "/hɔːs/"),
    createWord("Hospital", "noun", "Bệnh viện", "/ˈhɒspɪtl/"),
    createWord("Hour", "noun", "Giờ, đồng hồ", "/aʊə/"),
    createWord("House", "noun", "Ngôi nhà", "/haʊs/"),
    createWord("Humor", "noun", "Sự hài hước, sư hóm hỉnh", "/ˈhjuːmə/"),
    createWord("Ice", "noun", "Băng, đá", "/aɪs/"),
    createWord("Idea", "noun", "Ý tưởng, ý kiến, ý nghĩ", "/aɪˈdɪə/"),
    createWord("Impulse", "noun", "Sự thúc đẩy, động lực", "/ˈɪmpʌls/"),
    createWord("Industry", "noun", "Nền công nghiệp", "/ˈɪndəstri/"),
    createWord("Ink", "noun", "Mực", "/ɪŋk/"),
    createWord("Insect", "noun", "Côn trùng", "/ˈɪnsekt/"),
    createWord("Instrument", "noun", "Dụng cụ", "/ˈɪnstrəmənt/"),
    createWord("Insurance", "noun", "Bảo hiểm", "/ɪnˈʃʊərəns/"),
    createWord("Interest", "noun", "Sự thích, Lợi ích, Lãi suất", "/ˈɪntrɪst/"),
    createWord("Invention", "noun", "Sự phát minh", "/ɪnˈvenʃən/"),
    createWord("Iron", "noun", "Sắt", "/ˈaɪən/"),
    createWord("Island", "noun", "Hòn đảo", "/ˈaɪlənd/"),
    createWord("Jelly", "noun", "Thạch", "/ˈdʒeli/"),
    createWord("Jewel", "noun", "Đá quý, đồ trang", "/ˈdʒuːəl/"),
    createWord("Journey", "noun", "Chuyến đi", "/ˈdʒɜːni/"),
    createWord("Judge", "noun", "Thẩm phán", "/dʒʌdʒ/"),
    createWord("Kettle", "noun", "Ấm đun nước", "/ˈketl/"),
    createWord("Key", "noun", "Chìa khóa", "/kiː/"),
    createWord("Kick", "noun", "Cú đá", "/kɪk/"),
    createWord("Kind", "noun", "Kiểu mẫu, loại", "/kaɪnd/"),
    createWord("Kiss", "noun", "Nụ hôn", "/kɪs/"),
    createWord("Knee", "noun", "Đầu gối", "/niː/"),
    createWord("Knife", "noun", "Con dao", "/naɪf/"),
    createWord("Knot", "noun", "Nút", "/nɒt/"),
    createWord("Knowledge", "noun", "Kiến thức, hiểu biết", "/ˈnɒlɪdʒ/"),
    createWord("Land", "noun", "Đất liền", "/lænd/"),
    createWord("Language", "noun", "Ngôn ngữ, tiếng", "/ˈlæŋgwɪdʒ/"),
    createWord("Law", "noun", "Luật", "/lɔː/"),
    createWord("Leaf", "noun", "Lá cây", "/liːf/"),
    createWord("Learning", "noun", "Việc học tập", "/ˈlɜːnɪŋ/"),
    createWord("Leather", "noun", "Da", "/ˈleðə/"),
    createWord("Leg", "noun", "Chân", "/leg/"),
    createWord("Letter", "noun", "Lá thư", "/ˈletə/"),
    createWord("Level", "noun", "Trình độ, mức", "/ˈlevl/"),
    createWord("Library", "noun", "Thư viện", "/ˈlaɪbrəri/"),
    createWord("Lift", "noun", "Dàn, thang máy", "/lɪft/"),
    createWord("Limit", "noun", "Giới hạn, hạn chế", "/ˈlɪmɪt/"),
    createWord("Line", "noun", "Hàng dòng, đường", "/laɪn/"),
    createWord("Linen", "noun", "Vải lanh", "/ˈlɪnɪn/"),
    createWord("Lip", "noun", "Môi", "/lɪp/"),
    createWord("Liquid", "noun", "Chất lỏng", "/ˈlɪkwɪd/"),
    createWord("List", "noun", "Danh sách", "/lɪst/"),
    createWord("Living", "noun", "Cuộc sống, kế sinh nhai", "/ˈlɪvɪŋ/"),
    createWord("Lock", "noun", "Ổ khóa, ổ khóa, chốt lại", "/lɒk/"),
    createWord("Loss", "noun", "Sự thất bại, tốn kém, mất", "/lɒs/"),
    createWord("Machine", "noun", "Máy móc, thiết bị", "/məˈʃiːn/"),
    createWord("Market", "noun", "Chợ, thị trường", "/ˈmɑːkɪt/"),
    createWord("Match", "noun", "Trận đấu, que diêm", "/mætʃ/"),
    createWord("Material", "noun", "Chất liệu, nguyên liệu", "/məˈtɪərɪəl/"),
    createWord("Mass", "noun", "Lượng lớn, đồng", "/mæs/"),
    createWord("Meal", "noun", "Bữa ăn", "/miːl/"),
    createWord("Meet", "noun", "Thịt", "/miːt/"),
    createWord("Medical", "noun", "Khám sức khỏe", "/ˈmedɪkəl/"),
    createWord("Meeting", "noun", "Cuộc họp", "/ˈmiːtɪŋ/"),
    createWord("Memory", "noun", "Trí nhớ, sự, ức kí ức", "/ˈmeməri/"),
    createWord("Metal", "noun", "Kim loại", "/ˈmetl/"),
    createWord("Middle", "noun", "Ở giữa", "/ˈmɪdl/"),
    createWord("Military", "noun", "Quân sự, quân đội", "/ˈmɪlɪtəri/"),
    createWord("Milk", "noun", "Sữa", "/mɪlk/"),
    createWord("Mind", "noun", "Tâm trí, ý nghĩ", "/maɪnd/"),
    createWord("Mist", "noun", "Mù", "/mɪst/"),
    createWord("Mist", "noun", "Sương mù, màn", "/mɪst/"),
    createWord("Money", "noun", "Tiền", "/ˈmʌni/"),
    createWord("Monkey", "noun", "Con khỉ", "/ˈmʌŋki/"),
    createWord("Month", "noun", "Tháng", "/mʌnθ/"),
    createWord("Moon", "noun", "Tháng", "/muːn/"),
    createWord("Morning", "noun", "Buổi sáng", "/ˈmɔːnɪŋ/"),
    createWord("Mother", "noun", "Mẹ", "/ˈmʌðə/"),
    createWord("Motion", "noun", "Sự chuyển động", "/ˈməʊʃən/"),
    createWord("Mountain", "noun", "Ngọn núi", "/ˈmaʊntɪn/"),
    createWord("Mouth", "noun", "Miệng", "/maʊθ/"),
    createWord("Muscle", "noun", "Cơ, bắp", "/ˈmʌsl/"),
    createWord("Music", "noun", "Nhạc", "/ˈmjuːzɪk/"),
    createWord("Nail", "noun", "Móng tay", "/neɪl/"),
    createWord("Name", "noun", "Tên, tờ danh", "/neɪm/"),
    createWord("Nation", "noun", "Nước, quốc gia", "/ˈneɪʃən/"),

    // Batch 3: Words 309-471 (from third set of images)
    createWord("Neck", "noun", "Cổ", "/nek/"),
    createWord("Needle", "noun", "Cái kim", "/ˈniːdl/"),
    createWord("Nerve", "noun", "Nghị lực", "/nɜːv/"),
    createWord("Net", "noun", "Lưới, lưới", "/net/"),
    createWord("News", "noun", "Tin tức", "/njuːz/"),
    createWord("Night", "noun", "Đêm", "/naɪt/"),
    createWord("Noise", "noun", "Tiếng ồn", "/nɔɪz/"),
    createWord("North", "noun", "Phía Bắc", "/nɔːθ/"),
    createWord("Nose", "noun", "Mũi", "/nəʊz/"),
    createWord("Note", "noun", "Lời ghi chú, bức thư", "/nəʊt/"),
    createWord("Number", "noun", "Số lượng, con số", "/ˈnʌmbə/"),
    createWord("Nut", "noun", "Hạt", "/nʌt/"),
    createWord("Observation", "noun", "Sự quan sát, sự theo dõi", "/ˌɒbzəˈveɪʃən/"),
    createWord("Office", "noun", "Văn phòng", "/ˈɒfɪs/"),
    createWord("Oil", "noun", "Dầu", "/ɔɪl/"),
    createWord("Operation", "noun", "Ca phẫu thuật, sự hoạt động", "/ˌɒpəˈreɪʃən/"),
    createWord("Opinion", "noun", "Ý kiến, quan điểm", "/əˈpɪnjən/"),
    createWord("Orange", "noun", "Quả cam", "/ˈɒrɪndʒ/"),
    createWord("Order", "noun", "Thứ tự, trật tự, trật tự", "/ˈɔːdə/"),
    createWord("Organization", "noun", "Cơ quan, tổ chức", "/ˌɔːgənaɪˈzeɪʃən/"),
    createWord("Ornament", "noun", "Đồ trang trí", "/ˈɔːnəmənt/"),
    createWord("Oven", "noun", "Lò", "/ˈʌvən/"),
    createWord("Owner", "noun", "Chủ nhân", "/ˈəʊnə/"),
    createWord("Page", "noun", "Trang", "/peɪdʒ/"),
    createWord("Pain", "noun", "Sự đau đớn", "/peɪn/"),
    createWord("Paint", "noun", "Sơn", "/peɪnt/"),
    createWord("Paper", "noun", "Giấy", "/ˈpeɪpə/"),
    createWord("Parcel", "noun", "Gói, kiện hàng", "/ˈpɑːsl/"),
    createWord("Part", "noun", "Một phần", "/pɑːt/"),
    createWord("Past", "noun", "Quá khứ, truyởng", "/pɑːst/"),
    createWord("Payment", "noun", "Sự trả tiền, thanh toán", "/ˈpeɪmənt/"),
    createWord("Peace", "noun", "Hòa bình, thanh thản", "/piːs/"),
    createWord("Pen", "noun", "Chức bút", "/pen/"),
    createWord("Pencil", "noun", "Bút chì", "/ˈpensl/"),
    createWord("Person", "noun", "Con người", "/ˈpɜːsn/"),
    createWord("Picture", "noun", "Bức tranh", "/ˈpɪktʃə/"),
    createWord("Pig", "noun", "Con lợn", "/pɪg/"),
    createWord("Pin", "noun", "Đinh ghim", "/pɪn/"),
    createWord("Pipe", "noun", "Ống dẫn", "/paɪp/"),
    createWord("Plane", "noun", "Máy bay", "/pleɪn/"),
    createWord("Plant", "noun", "Thực vật, cây trồng", "/plɑːnt/"),
    createWord("Plate", "noun", "Đĩa", "/pleɪt/"),
    createWord("Play", "noun", "Vở kịch", "/pleɪ/"),
    createWord("Pleasure", "noun", "Niềm vui, điều thú", "/ˈpleʒə/"),
    createWord("Plough(plow)", "noun", "Cái cày", "/plaʊ/"),
    createWord("Pocket", "noun", "Túi quần", "/ˈpɒkɪt/"),
    createWord("Point", "noun", "Điểm", "/pɔɪnt/"),
    createWord("Poison", "noun", "Chất độc, thuốc", "/ˈpɔɪzn/"),
    createWord("Porter", "noun", "Người gác cổng, người khuân vác", "/ˈpɔːtər/"),
    createWord("Position", "noun", "Vị trí", "/pəˈzɪʃən/"),
    createWord("Pot", "noun", "Cái nồi, cái chậu", "/pɒt/"),
    createWord("Potato", "noun", "Khoai tây", "/pəˈteɪtəʊ/"),
    createWord("Powder", "noun", "Bột, phấn", "/ˈpaʊdə/"),
    createWord("Power", "noun", "Sức mạnh, quyền lực, sức", "/ˈpaʊə/"),
    createWord("Prison", "noun", "Mộng giá", "/ˈprɪzn/"),
    createWord("Price", "noun", "Giá", "/praɪs/"),
    createWord("Prison", "noun", "Tù ngục", "/ˈprɪzn/"),
    createWord("Process", "noun", "Quá trình, giai đoạn", "/ˈprəʊses/"),
    createWord("Produce/y", "noun", "Sản phẩm", "/ˈprɒdjuːs/"),
    createWord("Profit", "noun", "Lợi nhuận", "/ˈprɒfɪt/"),
    createWord("Property", "noun", "Tài sản", "/ˈprɒpəti/"),
    createWord("Prose", "noun", "Văn xuôi", "/prəʊz/"),
    createWord("Punishment", "noun", "Sự trừng phạt, hình phạt", "/ˈpʌnɪʃmənt/"),
    createWord("Purpose", "noun", "Mục đích", "/ˈpɜːpəs/"),
    createWord("Quality", "noun", "Chất lượng", "/ˈkwɒləti/"),
    createWord("Question", "noun", "Câu hỏi", "/ˈkwestʃən/"),
    createWord("Rail", "noun", "Đường sắt", "/reɪl/"),
    createWord("Range", "noun", "Dãy, loại", "/reɪndʒ/"),
    createWord("Rat", "noun", "Chuột cống", "/ræt/"),
    createWord("Rate", "noun", "Tỷ lệ", "/reɪt/"),
    createWord("Ray", "noun", "Tia", "/reɪ/"),
    createWord("Reaction", "noun", "Phản ứng", "/riˈækʃən/"),
    createWord("Reading", "noun", "Việc đọc sách", "/ˈriːdɪŋ/"),
    createWord("Reason", "noun", "Nguyên nhân, lý do", "/ˈriːzn/"),
    createWord("Receipt", "noun", "Hoá đơn", "/rɪˈsiːt/"),
    createWord("Record", "noun", "Số sách, hồ sơ, kỷ", "/ˈrekɔːd/"),
    createWord("Relation", "noun", "Mối quan hệ", "/rɪˈleɪʃən/"),
    createWord("Religion", "noun", "Tôn giáo, Đạo", "/rɪˈlɪdʒən/"),
    createWord("Representative", "noun", "Người đại diện, đại biểu", "/ˌreprɪˈzentətɪv/"),
    createWord("Request", "noun", "Lời yêu cầu", "/rɪˈkwest/"),
    createWord("Respect", "noun", "Sự kính trọng", "/rɪˈspekt/"),
    createWord("Reward", "noun", "Phần thưởng", "/rɪˈwɔːd/"),
    createWord("Rhythm", "noun", "Nhịp, nhịp điệu, sự", "/ˈrɪðəm/"),
    createWord("Rice", "noun", "Cây lúa, gạo", "/raɪs/"),
    createWord("Ring", "noun", "Chiếc nhẫn, cái vòng, vòng tròn", "/rɪŋ/"),
    createWord("River", "noun", "Sông", "/ˈrɪvə/"),
    createWord("Road", "noun", "Con đường", "/rəʊd/"),
    createWord("Roof", "noun", "Mái nhà", "/ruːf/"),
    createWord("Room", "noun", "Căn phòng", "/ruːm/"),
    createWord("Root", "noun", "Rễ cây", "/ruːt/"),
    createWord("Rub", "noun", "Luật", "/rʌb/"),
    createWord("Salt", "noun", "Muối", "/sɔːlt/"),
    createWord("Sand", "noun", "Cát", "/sænd/"),
    createWord("Scale", "noun", "Cái cân, quy mô", "/skeɪl/"),
    createWord("School", "noun", "Trường học", "/skuːl/"),
    createWord("Science", "noun", "Khoa học", "/ˈsaɪəns/"),
    createWord("Scissors", "noun", "Cái kéo", "/ˈsɪzəz/"),
    createWord("Screw", "noun", "Đinh vít, ốc vít", "/skruː/"),
    createWord("Sea", "noun", "Biển", "/siː/"),
    createWord("Seat", "noun", "Ghế ngồi, chỗ ngồi", "/siːt/"),
    createWord("Secret", "noun", "Điều bí mật", "/ˈsiːkrɪt/"),
    createWord("Secretary", "noun", "Thư ký", "/ˈsekrətri/"),
    createWord("Seed", "noun", "Hạt giống", "/siːd/"),
    createWord("Selection", "noun", "Sự lựa chọn", "/sɪˈlekʃən/"),
    createWord("Self (selves pl)", "noun", "Bản thân, cái bản", "/self/"),
    createWord("Servant", "noun", "Người hầu, người giúp việc, sư vụ", "/ˈsɜːvənt/"),
    createWord("Sex", "noun", "Giới, phái, giới tính", "/seks/"),
    createWord("Shade", "noun", "Bóng râm", "/ʃeɪd/"),
    createWord("Shame", "noun", "Sự xấu hổ, sự nhục nhã", "/ʃeɪm/"),
    createWord("Sheep", "noun", "Con cừu", "/ʃiːp/"),
    createWord("Shelf (shelves pl)", "noun", "Kệ, ngăn, giá", "/ʃelf/"),
    createWord("Ship", "noun", "Tàu thủy", "/ʃɪp/"),
    createWord("Shirt", "noun", "Áo sơ mi", "/ʃɜːt/"),
    createWord("Shock", "noun", "Sự sững chuẩn, cú chấn lớn", "/ʃɒk/"),
    createWord("Shoe", "noun", "Giày", "/ʃuː/"),
    createWord("Side", "noun", "Mạt, cạnh", "/saɪd/"),
    createWord("Sign", "noun", "Dấu hiệu, kí hiệu, bảng biển", "/saɪn/"),
    createWord("Silk", "noun", "Lụa", "/sɪlk/"),
    createWord("Sister", "noun", "Chị, em gái", "/ˈsɪstə/"),
    createWord("Size", "noun", "Kích cỡ, quy mô", "/saɪz/"),
    createWord("Skin", "noun", "Da", "/skɪn/"),
    createWord("Skirt", "noun", "Váy", "/skɜːt/"),
    createWord("Sky", "noun", "Bầu trời", "/skaɪ/"),
    createWord("Sleep", "noun", "Ngủ", "/sliːp/"),
    createWord("Slope", "noun", "Con dốc", "/sləʊp/"),
    createWord("Smile", "noun", "Nụ cười", "/smaɪl/"),
    createWord("Smoke", "noun", "Khói", "/sməʊk/"),
    createWord("Snake", "noun", "Con rắn", "/sneɪk/"),
    createWord("Snow", "noun", "Tuyết", "/snəʊ/"),
    createWord("Soap", "noun", "Xà bông, xà phòng", "/səʊp/"),
    createWord("Society", "noun", "Xã hội", "/səˈsaɪəti/"),
    createWord("Sock", "noun", "Tất vớ ngắn", "/sɒk/"),
    createWord("Son", "noun", "Con trai", "/sʌn/"),
    createWord("Song", "noun", "Bài hát", "/sɒŋ/"),
    createWord("Sound", "noun", "Âm thanh, tiếng động", "/saʊnd/"),
    createWord("South", "noun", "Hướng Nam, miền Nam", "/saʊθ/"),
    createWord("Soup", "noun", "Súp", "/suːp/"),
    createWord("Space", "noun", "Không gian, khoảng cách", "/speɪs/"),
    createWord("Spade", "noun", "Cái mai, cái thưỡng", "/speɪd/"),
    createWord("Spoon", "noun", "Cái thìa", "/spuːn/"),
    createWord("Spring", "noun", "Mùa xuân, sự bật", "/sprɪŋ/"),
    createWord("Square", "noun", "Hình vuông, quảng trường", "/skweə/"),
    createWord("Stage", "noun", "Sân khấu, giai đoạn", "/steɪdʒ/"),
    createWord("Stamp", "noun", "Tem, con dấu", "/stæmp/"),
    createWord("Star", "noun", "Ngôi sao", "/stɑː/"),
    createWord("Start", "noun", "Sự bắt đầu, sự khởi động", "/stɑːt/"),
    createWord("Statement", "noun", "Sự phát biểu, sự tuyên bố", "/ˈsteɪtmənt/"),
    createWord("Station", "noun", "Trạm, nhà ga", "/ˈsteɪʃən/"),
    createWord("Steam", "noun", "Hơi nước", "/stiːm/"),
    createWord("Stem", "noun", "Thân cây, cuống", "/stem/"),
    createWord("Steel", "noun", "Thép", "/stiːl/"),
    createWord("Step", "noun", "Bước, bước ôn tí, lối", "/step/"),
    createWord("Stick", "noun", "Cái gậy", "/stɪk/"),
    createWord("Stitch", "noun", "Mũi khâu, mũi dần", "/stɪtʃ/"),
    createWord("Stocking", "noun", "Vớ dài, bít tất dài", "/ˈstɒkɪŋ/"),
    createWord("Stomach", "noun", "Dạ dày, bụng", "/ˈstʌmək/"),
    createWord("Stone", "noun", "Đá, viên đá", "/stəʊn/"),
    createWord("Store", "noun", "Cửa hàng", "/stɔː/"),
    createWord("Story", "noun", "Câu chuyện", "/ˈstɔːri/"),
    createWord("Street", "noun", "Đường phố", "/striːt/"),
    createWord("Structure", "noun", "Cấu trúc, kết cấu", "/ˈstrʌktʃər/"),

    // Batch 4: Words 472-546 (from fourth set of images - includes Adjectives)
    createWord("Substance", "noun", "Chất liệu, thực chất", "/ˈsʌbstəns/"),
    createWord("Sugar", "noun", "Đường (mật mía hoặc củ cải)", "/ˈʃʊgə/"),
    createWord("Suggestion", "noun", "Sự đề xuất, sự gợi", "/səgˈdʒestʃən/"),
    createWord("Summer", "noun", "Mùa hè", "/ˈsʌmə/"),
    createWord("Sun", "noun", "Mặt trời", "/sʌn/"),
    createWord("Surprise", "noun", "Sự ngạc nhiên", "/səˈpraɪz/"),
    createWord("System", "noun", "Hệ thống", "/ˈsɪstəm/"),
    createWord("Table", "noun", "Cái bàn", "/ˈteɪbl/"),
    createWord("Tail", "noun", "Đuôi, đuôi cua", "/teɪl/"),
    createWord("Talk", "noun", "Tin đồn", "/tɔːk/"),
    createWord("Taste", "noun", "Vị", "/teɪst/"),
    createWord("Tax", "noun", "Thuế", "/tæks/"),
    createWord("Teaching", "noun", "Sự dạy, nghề dạy học, Học, Sự dạy dỗ", "/ˈtiːtʃɪŋ/"),
    createWord("Tendency", "noun", "Xu hướng, khuynh hướng", "/ˈtendənsi/"),
    createWord("Test", "noun", "Bài kiểm tra, kỳ thi, bài kiểm tra, sự thử", "/test/"),
    createWord("Theory", "noun", "Học thuyết, lý thuyết", "/ˈθɪəri/"),
    createWord("Thing", "noun", "Sự vật, vật", "/θɪŋ/"),
    createWord("Thought", "noun", "Suy nghĩ", "/θɔːt/"),
    createWord("Thread", "noun", "Sợi chỉ, sợi dây", "/θred/"),
    createWord("Throat", "noun", "Cổ họng", "/θrəʊt/"),
    createWord("Thumb", "noun", "Ngón tay cái", "/θʌm/"),
    createWord("Thunder", "noun", "Sấm đánh, tiếng động", "/ˈθʌndə/"),
    createWord("Ticket", "noun", "Vé, thẻ", "/ˈtɪkɪt/"),
    createWord("Time", "noun", "Thời gian", "/taɪm/"),
    createWord("Toe", "noun", "Ngón chân", "/təʊ/"),
    createWord("Tomorrow", "noun", "Ngày mai", "/təˈmɒrəʊ/"),
    createWord("Tongue", "noun", "Lưỡi, ngôn ngữ", "/tʌŋ/"),
    createWord("Tooth (teeth pl)", "noun", "Răng", "/tuːθ/"),
    createWord("Top", "noun", "Đỉnh, chóp", "/tɒp/"),
    createWord("Town", "noun", "Thị trấn, thị xã", "/taʊn/"),
    createWord("Trade", "noun", "Thương mại, sự buôn bán", "/treɪd/"),
    createWord("Train", "noun", "Xe lửa", "/treɪn/"),
    createWord("Tray", "noun", "Cái khay, ngăn hộm", "/treɪ/"),
    createWord("Tree", "noun", "Cây", "/triː/"),
    createWord("Trick", "noun", "Mưu, trò, mẹo, thủ thuật, sự lừa mạn, né tránh", "/trɪk/"),
    createWord("Trouble", "noun", "Điều bực mình, khó khăn, rắc rối", "/ˈtrʌbl/"),
    createWord("Trousers", "noun", "Quần", "/ˈtraʊzəz/"),
    createWord("Umbrella", "noun", "Cái ô, cái dù", "/ʌmˈbrelə/"),
    createWord("Unit", "noun", "Đơn vị", "/ˈjuːnɪt/"),
    createWord("Value", "noun", "Giá trị", "/ˈvæljuː/"),
    createWord("Verse", "noun", "Thơ", "/vɜːs/"),
    createWord("Vessel", "noun", "Bình, chậu, chai, thùng, tàu thủy", "/ˈvesl/"),
    createWord("View", "noun", "Tầm nhìn, quang cảnh, quan điểm", "/vjuː/"),
    createWord("Voice", "noun", "Giọng nói, tiếng nói", "/vɔɪs/"),
    createWord("Waiting", "noun", "Sự chờ đợi", "/ˈweɪtɪŋ/"),
    createWord("Wall", "noun", "Tường, vách", "/wɔːl/"),
    createWord("War", "noun", "Chiến tranh", "/wɔː/"),
    createWord("Water", "noun", "Nước", "/ˈwɔːtə/"),
    createWord("Wave", "noun", "Sóng", "/weɪv/"),
    createWord("Wax", "noun", "Sáp", "/wæks/"),
    createWord("Way", "noun", "Đường đi, cách", "/weɪ/"),
    createWord("Weather", "noun", "Thời tiết", "/ˈweðə/"),
    createWord("Week", "noun", "Tuần, tuần lễ", "/wiːk/"),
    createWord("Weight", "noun", "Sức nặng, trọng lượng", "/weɪt/"),
    createWord("West", "noun", "Hướng tây", "/west/"),
    createWord("Wheel", "noun", "Bánh xe, vô-lăng", "/wiːl/"),
    createWord("Whip", "noun", "Roi, roi da", "/wɪp/"),
    createWord("Whistle", "noun", "Tiếng huýt sáo (giọt)", "/ˈwɪsl/"),
    createWord("Will", "noun", "Ý chí", "/wɪl/"),
    createWord("Wind", "noun", "Gió", "/wɪnd/"),
    createWord("Window", "noun", "Cửa sổ", "/ˈwɪndəʊ/"),
    createWord("Wine", "noun", "Rượu vang, rượu", "/waɪn/"),
    createWord("Wing", "noun", "Cánh (chim, máy bay)", "/wɪŋ/"),
    createWord("Winter", "noun", "Mùa đông", "/ˈwɪntə/"),
    createWord("Wire", "noun", "Dây (kim loại)", "/ˈwaɪə/"),
    createWord("Woman (women pl)", "noun", "Đàn bà, phụ nữ", "/ˈwʊmən/"),
    createWord("Wood", "noun", "Gỗ, củi", "/wʊd/"),
    createWord("Wool", "noun", "Len, sợi len", "/wʊl/"),
    createWord("Word", "noun", "Từ ngữ, lời nói", "/wɜːd/"),
    createWord("Worm", "noun", "Con giun, đường sâu, con trùng", "/wɜːm/"),
    createWord("Wound", "noun", "Vết thương, vết thương nhãn", "/wuːnd/"),
    createWord("Writing", "noun", "Chữ viết, sự viết, văn viết, bài văn của mình", "/ˈraɪtɪŋ/"),
    createWord("Year", "noun", "Năm", "/jɪə/"),
    createWord("Yesterday", "noun", "Hôm qua", "/ˈjestədeɪ/"),

    // Adjectives section
    createWord("Able", "adjective", "Có khả năng việc gì", "/ˈeɪbl/"),
    createWord("Angry", "adjective", "Tức giận, giận dữ", "/ˈæŋgri/"),
    createWord("Automatic", "adjective", "Tự động", "/ˌɔːtəˈmætɪk/"),
    createWord("Bad", "adjective", "Tồi tệ", "/bæd/"),
    createWord("Beautiful", "adjective", "Xinh đẹp", "/ˈbjuːtɪful/"),
    createWord("Bent", "adjective", "Cong", "/bent/"),
    createWord("Bitter", "adjective", "Đắng, đau đớn", "/ˈbɪtə/"),
    createWord("Black", "adjective", "Đen", "/blæk/"),
    createWord("Blue", "adjective", "Màu xanh da trời", "/bluː/"),
    createWord("Boiling", "adjective", "Đang sôi", "/ˈbɔɪlɪŋ/"),
    createWord("Bright", "adjective", "Sáng, bóng", "/braɪt/"),
    createWord("Broken", "adjective", "Bị hỏng, bị gãy", "/ˈbrəʊkən/"),
    createWord("Brown", "adjective", "Màu nâu", "/braʊn/"),
    createWord("Certain", "adjective", "Một chứng minh chủ do, chắc chắn", "/ˈsɜːtn/"),
    createWord("Cheap", "adjective", "Rẻ, giả mạo", "/tʃiːp/"),
    createWord("Chemical", "adjective", "Thuộc về hóa học", "/ˈkemɪkəl/"),
    createWord("Clean", "adjective", "Sạch sẽ, trong sạch", "/kliːn/"),
    createWord("Clear", "adjective", "Rõ ràng, sáng tỏ hiểu", "/klɪə/"),
    createWord("Cold", "adjective", "Lạnh", "/kəʊld/"),
    createWord("Common", "adjective", "Phổ biến, thông thường", "/ˈkɒmən/"),
    createWord("Complex", "adjective", "Phức tạp, rắc rối", "/ˈkɒmpleks/"),
    createWord("Conscious", "adjective", "Có ý thức, nhận ra", "/ˈkɒnʃəs/"),
    createWord("Copper", "adjective", "Bằng đồng", "/ˈkɒpə/"),
    createWord("Cruel", "adjective", "Tàn nhẫn, hiểm nghèo", "/ˈkruːəl/"),
    createWord("Current", "adjective", "Hiện tại, hiện nay", "/ˈkʌrənt/"),
    createWord("Dark", "adjective", "Tối", "/dɑːk/"),
    createWord("Dead", "adjective", "Chết, mất", "/ded/"),
    createWord("Dear", "adjective", "Thân thiết, có giá trị", "/dɪə/"),
    createWord("Deep", "adjective", "Sâu", "/diːp/"),
    createWord("Delicate", "adjective", "Mềm mại, mỏng manh", "/ˈdelɪkət/"),
    createWord("Dependent", "adjective", "Phụ thuộc", "/dɪˈpendənt/"),
    createWord("Different", "adjective", "Khác nhau", "/ˈdɪfrənt/"),
    createWord("Dirty", "adjective", "Bẩn thỉu", "/ˈdɜːti/"),
    createWord("Dry", "adjective", "Khô, khô cằn", "/draɪ/"),
    createWord("Electric", "adjective", "Bằng điện", "/ɪˈlektrɪk/"),
    createWord("Equal", "adjective", "Tương đương", "/ˈiːkwəl/"),
    createWord("False", "adjective", "Sai", "/fɔːls/"),
    createWord("Fat", "adjective", "Béo", "/fæt/"),
    createWord("Feeble", "adjective", "Nhụ nhược", "/ˈfiːbl/"),
    createWord("Fertile", "adjective", "Màu mỡ, phì nhiêu", "/ˈfɜːtaɪl/"),
    createWord("First", "adjective", "Thứ nhất, đầu tiên", "/fɜːst/"),
    createWord("Fixed", "adjective", "Cố định", "/fɪkst/"),
    createWord("Foolish", "adjective", "Dại dột, ngu xuẩn", "/ˈfuːlɪʃ/"),
    createWord("Free", "adjective", "Tự do, miễn phí", "/friː/"),
    createWord("Frequent", "adjective", "Thường xuyên", "/ˈfriːkwənt/"),
    createWord("Full", "adjective", "Đầy", "/fʊl/"),
    createWord("General", "adjective", "Chung, phổ biến", "/ˈdʒenərəl/"),
    createWord("Good", "adjective", "Tốt, hay", "/gʊd/"),
    createWord("Great", "adjective", "Tuyệt vời lắm", "/greɪt/"),
    createWord("Green", "adjective", "Màu xanh lá cây", "/griːn/"),
    createWord("Grey/gray", "adjective", "Màu xám", "/greɪ/"),
    createWord("Happy", "adjective", "Hạnh phúc, vui vẻ", "/ˈhæpi/"),
    createWord("Hard", "adjective", "Khó, cứng", "/hɑːd/"),
    createWord("Healthy", "adjective", "Khỏe mạnh", "/ˈhelθi/"),
    createWord("High", "adjective", "Cao", "/haɪ/"),
    createWord("Hollow", "adjective", "Rỗng tuệch, lòm xuống", "/ˈhɒləʊ/"),
];

export async function addBasicWords() {
    console.log("Adding 850 Basic Words deck...");

    try {
        await prisma.deck.upsert({
            where: { id: deckId },
            update: {},
            create: {
                id: deck.id,
                name: deck.name,
                description: deck.description,
                category: deck.category,
                totalWords: deck.totalWords,
                version: deck.version,
                language: deck.language
            }
        });
        console.log("Deck ensured.");

        let count = 0;
        console.log(`Processing ${words.length} words...`);

        // Process in batches to avoid connection timeout
        const BATCH_SIZE = 50;
        for (let i = 0; i < words.length; i += BATCH_SIZE) {
            const batch = words.slice(i, i + BATCH_SIZE);
            await Promise.all(batch.map(async (w) => {
                const existing = await prisma.wordEntry.findFirst({
                    where: {
                        deckId: deckId,
                        headword: { equals: w.headword } // SQLite was case-insensitive by default, Postgres needs explicit mode if we want it, but exact match is fine for now or we can use mode: 'insensitive'
                    }
                });

                if (!existing) {
                    await prisma.wordEntry.create({
                        data: {
                            id: uuid(),
                            deckId: deckId,
                            headword: w.headword,
                            partOfSpeech: w.partOfSpeech,
                            meaningVi: w.meaningVi,
                            // phonetic: w.phonetic, // Schema doesn't have phonetic yet
                            exampleEn: w.exampleEn || `Example for ${w.headword}`,
                            exampleVi: w.exampleVi || `Ví dụ cho ${w.headword}`,
                            picturable: false
                        }
                    });
                    count++;
                }
            }));
        }
        console.log(`Added ${count} new words.`);
    } catch (error) {
        console.error("Error adding words:", error);
        throw error;
    }
}
